### PR TITLE
Add break hours for calculating actual working hours

### PR DESCRIPTION
**Pull request by roquegv**
Solving https://github.com/phamos-eu/HR-Addon/issues/26

What is included:
- Add `break_minutes` in Weekly Working Hours' child table.
Captura de pantalla de 2023-05-08 15-48-16

- Add "Expected Break Hours" and "Actual Working Hours" to Workday form.
Captura de pantalla de 2023-05-08 15-47-59

- Get "Expected Break Hours" and calculate "Actual Working Hours" within Workday form.
Kazam_screencast_00032

- Get "Expected Break Hours" and calculate "Actual Working Hours" within Workday list (using Process Workdays button).
Kazam_screencast_00033

- Update "Work Hour Report": add "Actual Working Hours", "Expected Break Hours", "Diff (Work Hours - Target Seconds)" and "Diff (Actual Working Hours - Target Seconds)" columns
Captura de pantalla de 2023-05-08 15-52-25

### CODE REVIEW

**Comment by wojosc** [comment]
@roquegv please do not PR into version-14 without having it thorowly tested first. I advice to create a "develop" branch and do the testing there first. @reggaetuna will then test this in a frappecloud instance. Once you have run all your tests, you can PR into version-14. Thank you.

**Comment by roquegv** [comment]
@wojosc ok, I'll do that :+1:

**Comment by roquegv** [comment]
@wojosc could you please create a branch for making the pull request? I have no permissions to do that.
will be good to have a develop branch from version-14

**Comment by wojosc** [comment]
@roquegv https://github.com/phamos-eu/HR-Addon/tree/develop done

Please be aware, that version-13 and master/main differ and probably can not be used in the same way. Let me know if you need any further branches. Also, I will check to make sure, that you have the permissions to do the same. Thanks.

**Pull request closed without merging**
